### ISSUE TITLE
One cpu thread load at 100% non-stop

### ISSUE THREAD

**Issue by jurgis-upenieks** [mallowigi/material-theme-jetbrains-eap#143] opened 2017-08-21 11:23 UTC
On all versions after version 0.8.1.1 (not including), I am having an issue, that one of cpu threads is at 100% load non-stop. I tested on webstorm and on rider, so it is possible that this might be global for all jetbrains IDEs. I tested that this issue happens on all versions after 0.8.1.1 - 0.9.0, 0.9.1, 0.9.1.1 and 0.9.1.2 - I explicitly retested on all of those versions. As a workaround, I reverted to 0.8.1.1.

**Comment by mallowigi** [comment] 2017-08-21 11:38
Which OS? Which IDE (EAP?)

I'm on Webstorm right now and I don't see something out of the ordinary.

Also, which material settings are you using?

**Comment by jurgis-upenieks** [comment] 2017-08-21 11:44
My OS is Linux - Ubuntu 16.04.3 LTS xenial.
My Webstorm version is 2017.2.2 172.3757.55
![screenshot from 2017-08-21 14-44-11](https://user-images.githubusercontent.com/13751845/29517760-45a4467c-867f-11e7-9bec-1deffc0a8f55.png)

**Comment by mallowigi** [comment] 2017-08-21 14:47
Ok I managed to reproduce it o.O it's very annoying

**Comment by mallowigi** [comment] 2017-08-21 18:19
Ok can you check with the latest version? I think I found it.

**Comment by jurgis-upenieks** [comment] 2017-08-22 06:48
I checke with 0.9.2, but it has the same issue. One of cpu threads is at 100% load non-stop.
![screenshot from 2017-08-22 09-44-43](https://user-images.githubusercontent.com/13751845/29552208-fa1c46aa-871e-11e7-9a26-0d0b13468bf3.png)

**Comment by mallowigi** [comment] 2017-08-22 08:40
Sadly I can't reproduce... What kind of project is this? Typescript? React?

**Comment by jurgis-upenieks** [comment] 2017-08-22 09:48
It is angular/typescript project, but I don't think that this issue is project or even IDE specific, because it happens also on other jetbrains IDEs, at least on Rider, as I have tested.

**Comment by mallowigi** [comment] 2017-08-22 10:09
I am currently working on Mac and I've tried PHP projects, JS projects, Ruby and Java projects and it doesn't consume all CPU so far.

I found the previous issue occuring on Java projects only, that's why I asked.

It could be related to the OS, though it happens also on Windows according to another thread.

**Comment by mallowigi** [comment] 2017-08-22 10:21
[Material Theme.zip](https://github.com/mallowigi/material-theme-jetbrains-eap/files/1241672/Material.Theme.zip)

Can you try to install the plugin from the zip file attached and tell me if there is an amelioration? Thanks

**Comment by jurgis-upenieks** [comment] 2017-08-22 11:32
I uninstalled existing plugin version (0.8.1.1), restarted webstorm, installed the zip file from your link, restarted webstorm, but the issue was not gone.

**Comment by mallowigi** [comment] 2017-08-22 14:38
I think I found it, and I understand now why it happens only on non-mac.

Please try it now
[Material Theme.zip](https://github.com/mallowigi/material-theme-jetbrains-eap/files/1242351/Material.Theme.zip)

**Comment by mallowigi** [comment] 2017-08-22 14:41
[Material Theme.zip](https://github.com/mallowigi/material-theme-jetbrains-eap/files/1242364/Material.Theme.zip)

**Comment by jurgis-upenieks** [comment] 2017-08-22 14:46
still having the issue

**Comment by jurgis-upenieks** [comment] 2017-08-22 14:48
I downloaded the latest link twice to make sure

**Comment by jurgis-upenieks** [comment] 2017-08-22 15:17
Maybe the last link is pointing to some older version?

**Comment by mallowigi** [comment] 2017-08-22 15:22
[Material Theme.zip](https://github.com/mallowigi/material-theme-jetbrains-eap/files/1242490/Material.Theme.zip)
Just to make sure. The plugin version should be 0.9.2.test2

**Comment by jurgis-upenieks** [comment] 2017-08-23 06:54
I installed the 0.9.2.test2, restarted webstorm, but the issue is still there. I checked in settings/plugins, and the versions is really 0.9.2.test2. Reverted back to 0.8.1.1, and the issue is fully gone again.

**Comment by iwex** [comment] 2017-08-23 09:04
Same issue 
![image](https://user-images.githubusercontent.com/4510068/29607885-4445ce68-87fb-11e7-851c-0a736d2c17cb.png)

**Comment by jurgis-upenieks** [comment] 2017-08-23 14:27
There might be some HDD read/write operation infinite looping, because on faster HDDs the CPU is loaded more (100% load), and on slower HDDs the CPU is loaded less (30% - 100%). In each loop iteration CPU might be initially waiting for HDD read/write operation to complete, so this acts like sleep for process thread.

**Comment by mallowigi** [comment] 2017-08-23 18:03
For sure, as long as I know where is that infinite looping is occurring :) I've tried removing the whole "uppercase tabs" feature but you told me that wasn't the case. This was the big change of 9.0 along with the debugger tab height fix and the custom accent color (could that be it?)

**Comment by mallowigi** [comment] 2017-08-24 10:33
I've checked in Windows and Linux and didn't see something out of the ordinary. I really don't know how to fix this...

**Comment by mallowigi** [comment] 2017-08-24 10:33
Can you lot send me your material_theme.xml config? And list of plugins?

**Comment by jurgis-upenieks** [comment] 2017-08-24 10:56
Here is my material_theme.xml
[material_theme.xml.zip](https://github.com/mallowigi/material-theme-jetbrains-eap/files/1248564/material_theme.xml.zip)
I will just stay with 0.8.1.1

**Comment by mallowigi** [comment] 2017-08-25 17:51
I'm at loss... the only thing I can "do" would be to ask you to download the project and install it locally, then build the plugin for every commit since version 8.1 to pinpoint the problematic commit since it is not reproducible in my environment, but you'd need an IntelliJ Ultimate licence, plus to be able to install the project on your computer...

**Comment by mallowigi** [comment] 2017-08-28 14:36
lol I found the problem (thanks to @iwex)

That's s crazy! The problem is because you are in Tabs placement left!

I will post an update soon

**Comment by mallowigi** [comment] 2017-08-28 18:54
[Material Theme.zip](https://github.com/mallowigi/material-theme-jetbrains-eap/files/1257859/Material.Theme.zip)
Hi, Sorry to ask again but can you check with this updated version?

**Comment by jurgis-upenieks** [comment] 2017-08-29 07:03
Plugin from the link doesn't fix the issue, and same for 0.9.3.

**Comment by mallowigi** [comment] 2017-08-29 08:35
Should be fixed now, thanks @iwex

**Closed by mallowigi** 2017-08-29 08:35 UTC
Labels: cannot-reproduce

**Comment by jurgis-upenieks** [comment] 2017-08-30 06:55
I just tested with 0.9.3.4, and the issue is gone in that version.
