### ISSUE TITLE
ignored directories not grayed out with .ignore plugin

### ISSUE THREAD

**Issue by nazrhyn** [mallowigi/material-theme-jetbrains-eap#197] opened 2017-11-10 14:19 UTC
_I noticed this one while I was testing the file color changes for #196._

------

### Summary
When Material Theme is active, ignored directories do not appear to get grayed out. Here's the behavior with Material off:   
![ignore-folders-darkula](https://user-images.githubusercontent.com/1672405/32662253-e1e9a7ae-c5f7-11e7-8544-fa6c868cac9e.gif)

Here's the behavior with it on, using the Darker theme:   
![ignore-folders-material](https://user-images.githubusercontent.com/1672405/32662270-ecbcb3ec-c5f7-11e7-932c-93839d8785de.gif)

You can see the file getting its gray color, but not the directory. I did not try this in the other themes.

### Expected behavior
Both files and directories are grayed out when they should be based on the **.gitignore** file.

### Actual behavior
Only files are grayed out.

### Environment
WebStorm 2017.2.5
Build #WS-172.4343.25, built on October 20, 2017
JRE: 1.8.0_152-release-915-b12 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.10.0-38-generic

Material Theme UI EAP 1.2.1-pre
Configuration: https://gist.github.com/nazrhyn/b005065d2ba1ca58dc64f9beb950f2e6

.ignore 2.3.0

**Comment by mallowigi** [comment] 2017-11-10 15:52
Duplicate of https://github.com/ChrisRM/material-theme-jetbrains/issues/477

**Comment by nazrhyn** [comment] 2017-11-10 16:17
Not a duplicate.

>Files ignored by the .ignore plugin do not get any special colour.

In this issue, I'm showing files getting a special color but _folders_ not getting one.

**Comment by mallowigi** [comment] 2017-11-10 19:20
Ah you were talking about directories... well I will see what I can do, maybe gitignore have an api to see which folders are ignored

**Comment by nazrhyn** [comment] 2017-11-10 19:27
Updated first post and title to use "directory" instead of "folder" :wink:.

**Closed** 2017-11-19 09:48 UTC
