### ISSUE TITLE
Can't open Projects while this theme is enabled

### ISSUE THREAD

**Issue by detwetter** [mallowigi/material-theme-jetbrains-eap#145] opened 2017-08-22 14:19 UTC
### Summary

While this theme is enabled, I am unable to open existing projects.  If I select to open in a new window, nothing happens.  If I select to open in the existing window, it closes the existing project.  If I disable this theme, everything works as expected.

If I start minimizing all open projects, once the last project is minimized, the project I tried to open is now launched in a new window.  This is very strange.

I'm not seeing any errors being thrown.

### Environment

PhpStorm 2017.2.1
Build #PS-172.3544.41, built on August 2, 2017
Subscription is active until April 1, 2018
JRE: 1.8.0_152-release-915-b6 x86
JVM: OpenJDK Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by mallowigi** [comment] 2017-08-22 18:09
Can't reproduce on Mac. 

Will try on Windows as soon as i can.

**Comment by detwetter** [comment] 2017-08-23 11:23
OK, thanks!

This isn't a huge deal once I found out that if I minimize all open projects, the one I tried to just open, will open.

**Comment by mallowigi** [comment] 2017-08-24 10:49
Cannot reproduce (again)

What plugins do you have?

**Comment by mallowigi** [comment] 2017-08-24 11:19
![newwin](https://user-images.githubusercontent.com/5015756/29663295-00e9ade6-88d3-11e7-9dd7-ed18988dda45.gif)

**Comment by detwetter** [comment] 2017-08-24 11:26
![capture2](https://user-images.githubusercontent.com/29411391/29664429-85bd3ac8-889d-11e7-8afc-1a55efcc9be4.JPG)
![capture](https://user-images.githubusercontent.com/29411391/29664428-85b84dc4-889d-11e7-842b-2db592ccd809.JPG)

**Comment by detwetter** [comment] 2017-08-24 11:39
I wouldn't put too much effort into this as I have a workaround that's not that much effort at all.

**Comment by mallowigi** [comment] 2017-08-24 11:56
Cannot reproduce, and I'm on Windows 10 as well... weird bugs.

Have you tried opening and closing PHPstorm?

**Comment by mallowigi** [comment] 2017-08-24 11:57
maybe there is a setting for that?

**Comment by detwetter** [comment] 2017-08-24 12:03
Yeah, I have shutdown and restarted many times.  As soon as I disable the Material Theme it works fine.  With the Material Theme enabled, I have to minimize all open projects in order to get the project I just selected to open.  Of note, I used to use Full Screen mode all the time, but had to turn that off in order to minimize the open projects.  That may have some affect on this.

**Comment by mallowigi** [comment] 2017-08-24 12:35
Sorry, Cannot reproduce.

**Comment by mallowigi** [comment] 2017-08-24 12:51
perhaps there is an issue with your material config file. Try to delete it manually and tell me if it changes anything

**Comment by detwetter** [comment] 2017-08-24 13:09
Is that:
.PhpStorm2017.2\config\settingsRepository\repository\material_theme.xml

**Comment by mallowigi** [comment] 2017-08-24 13:10
hum no, but config/options/material_theme.xml

**Comment by detwetter** [comment] 2017-08-24 13:26
For me that file only exists in .PhpStorm2017.2\config\settingsRepository\repository\
Must be the same file.

**Comment by mallowigi** [comment] 2017-08-24 14:11
perhaps... does it change anything ?

**Comment by detwetter** [comment] 2017-08-28 12:31
Deleting this file did not have a change to the problem.

**Comment by mallowigi** [comment] 2017-08-28 14:36
lol I found the problem (thanks to @iwex) 

That's s crazy! The problem is because you are in Tabs placement left!

I will post an update soon

**Comment by mallowigi** [comment] 2017-08-29 07:14
Can you try with latest release?

**Comment by detwetter** [comment] 2017-08-29 12:25
Sweet, it's fixed now!  Works perfectly!!  Thanks @mallowigi !!!!

**Comment by detwetter** [comment] 2017-08-29 12:27
I'm guessing not a lot of people like the Tabs down the sides!  8-)

**Closed** 2017-08-29 13:04 UTC
Labels: cannot-reproduce
