### ISSUE TITLE
Matherial Theme loads my CPU

### ISSUE THREAD

**Issue by fatalist** [mallowigi/material-theme-jetbrains-eap#144] opened 2017-08-22 08:00 UTC
I noticed that plugin is dramatically loads my CPU. It happened about two weeks ago. A always use the latest version of plugin. It varies between 28% and 55%. When I disable the theme plugin CPU load becomes normal.
Windows 10 PRO
Intel Core i7-6700HQ @ 2.60GHz
16 GB RAM
![default](https://user-images.githubusercontent.com/313991/29554598-6862a01a-8728-11e7-8c2a-2714aa2a9631.png)
![default](https://user-images.githubusercontent.com/313991/29554630-8b58ae16-8728-11e7-947f-318d7b88d4da.png)
![default](https://user-images.githubusercontent.com/313991/29554694-c4d61f52-8728-11e7-871d-78b6c0a20f86.png)

**Comment by mallowigi** [comment] 2017-08-22 08:07
Duplicate of https://github.com/mallowigi/material-theme-jetbrains-eap/issues/143#issuecomment-323935273

**Closed by mallowigi** 2017-08-22 08:07 UTC
